config/routes.rb
# For details on the DSL available within this file, 
# see https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]  

  root 'welcome#index'

  get 'my_portfolio',  to: 'users#my_portfolio'
  get 'search_stock',  to: 'company_stocks#search'
  resources :user_stocks,  only: [:create, :destroy]

  get 'my_friends',    to: 'users#my_friends'
  get 'search_friend', to: 'users#search'
  resources :user_friends, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company_stock.rb
require 'net/http'
require 'json'

class CompanyStock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks
  
  validates :name, :ticker, presence: true

  def self.check_db(ticker_symbol) 
    where(ticker: ticker_symbol).first
  end 

  def self.price_lookup(ticker_symbol)
    stock_prices = get_data('eod', ticker_symbol)
    stock_prices['close']
  end 

  def self.stock_lookup(ticker_symbol) 
    company_info = get_data('tickers', ticker_symbol)
    stock_prices = get_data('eod',     ticker_symbol)

    if company_info && stock_prices
      new(
        ticker: ticker_symbol, 
        name: company_info['name'], 
        last_price: stock_prices['close'],
      )
    else 
      nil
    end
  end

  private

  def self.get_data(endpoint, ticker_symbol)
    params = { 
      :access_key => Rails.application.credentials.market_stack[:api_key], 
      :symbols    => "#{ticker_symbol}",
      :limit      => 1 
    }
    path      = endpoint.eql?('eod')? "eod" : "tickers/#{ticker_symbol}"
    uri       = URI("http://api.marketstack.com/v1/#{path}")
    uri.query = URI.encode_www_form(params)
    json      = Net::HTTP.get(uri)
    full_data = JSON.parse(json)

    begin    
       ret_data = endpoint.eql?('eod')? full_data['data'].first : full_data
       
    rescue => exception
      nil
    end
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :company_stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  # USER STOCKS       
  def can_track_another_stock?(current_user, ticker_symbol) 
    under_stock_limit?(current_user) && !stock_already_tracked?(current_user, ticker_symbol)
  end 

  def stock_already_tracked?(current_user, ticker_symbol) 
    company_stock = CompanyStock.check_db(ticker_symbol)

    return false unless company_stock

    #company_stocks.where(id: stock.id).exists?
    stock = UserStock.where(user_id: current_user.id, company_stock_id: company_stock.id).first
    
    return false if stock.blank?
    true
  end 

  def under_stock_limit?(current_user) 
    #company_stocks.count < 10
    UserStock.where(user_id: current_user.id).count < 10
  end


  # USER FRIENDS
  def self.friend_lookup(current_user, search_term)
    search_term.downcase.strip 

    friends = where("LOWER(first_name) like ?", "%#{search_term}%")
      .or(    where("LOWER(last_name) like ?", "%#{search_term}%") )
      .or(    where("LOWER(email) like ?", "%#{search_term}%") )
      .uniq

    friends = friends.reject { |x| x.id == current_user.id }

    return (friends)? friends : nil
  end

  def friend_already_displayed?(friend) 
    self.friends.where(id: friend.id).exists?
  end 

  def full_name 
    return "#{first_name} #{last_name}".strip if first_name || last_name
    "Anonymous"
  end 

  def under_friend_limit? 
    self.friends.count < 10
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :company_stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters 
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/company_stocks_controller.rb
class CompanyStocksController < ApplicationController

  def search 
    if params[:stock].present?
      ticker = params[:stock].strip
      @stock = CompanyStock.stock_lookup(ticker)
      
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/stock_result' }
        end 
      else 
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid stock symbol"
          format.js { render partial: 'users/stock_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a stock symbol"
        format.js { render partial: 'users/stock_result' }
      end
    end 
  end
end

app/controllers/user_friends_controller.rb
class UserFriendsController < ApplicationController
   def create 
    # Add friend to list of tracked friends (create a list item)
    friendship     = current_user.friendships.create(friend_id: params[:friend])
    
    @friend        = User.find(friendship.friend_id)
    flash[:notice] = "Following #{full_name}"

    redirect_to my_friends_path
  end 

  def destroy 
    # Remove friend from list of tracked friends (remove list item)
    current_user.friendships.where(friend_id: params[:id]).first.destroy

    @friend        = User.find(params[:id])
    flash[:notice] = "No longer following #{full_name}"

    redirect_to my_friends_path
  end

  def full_name 
    return "#{@friend.first_name} #{@friend.last_name}".strip if @friend.first_name || @friend.last_name
    "Anonymous"
  end 
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create 
    # Add stock to list of tracked stocks

    ticker = params[:ticker].upcase
    stock  = CompanyStock.check_db(ticker)

    if stock.blank? || stock.last_price.nil?
      # We are not tracking this stock, or the price was not fetched in early development.
      # Call 3rd party API to look up stock info.
      stock = CompanyStock.stock_lookup(ticker)
      stock.save
    end  

    @user_stock    = UserStock.create(user: current_user, company_stock: stock)
    flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio."

    redirect_to my_portfolio_path
  end 

  def destroy 
    # Remove stock from list of tracked stocks
    stock      = CompanyStock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, company_stock_id: stock.id).first

    user_stock.destroy

    flash[:notice] = "#{stock.ticker} was successfully removed from your portfolio."

    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_friends
    @tracked_friends = current_user.friends
  end

  def my_portfolio
    @user           = current_user
    @tracked_stocks = get_latest_stock_prices(current_user.company_stocks)
  end

  def search 
    if params[:friend].present?
      @friends = User.friend_lookup(current_user, params[:friend])

      if !@friends.blank?
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end 
      else 
        respond_to do |format|
          flash.now[:alert] = "The friend was not found"
          format.js { render partial: 'users/friend_result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend's name"
        format.js { render partial: 'users/friend_result' }
      end
    end 
  end

  def show 
    @user           = User.find(params[:id]) 
    stocks          = @user.user_stocks 
    @tracked_stocks = stocks.map { |stock| CompanyStock.find(stock.company_stock_id) }
    @tracked_stocks = get_latest_stock_prices(@tracked_stocks)
  end  

  private

  def get_latest_stock_prices(tracked_stocks) 
    tracked_stocks.each { |stock| stock.last_price = CompanyStock.price_lookup(stock.ticker) }
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_list.html.erb
<div class="row">
  <div class="col-9">
    <br/>
    <strong>Following Friends: </strong>

    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Email</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_friends.each do |user| %>
          <tr>
            <td><%= user.first_name + ' ' + user.last_name %></td>
            <td><%= user.email %></td>
            <td>
              <%= link_to 'View Profile', user_path(id: user.id),
                      class: 'btn btn-sm btn-success' %>
              <%= link_to 'Unfollow', user_friend_path(user.id), method: :delete, 
                      data: {confirm: 'Are you sure?'},
                      class: 'btn btn-sm btn-warning' %>
            </td>
          </tr>
        <% end %>  
      </tbody>
    </table>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% if notice && !notice.empty? %>
  <div class="alert alert-success" role="alert">
    <span class="notice"><%= notice %></span>
  </div>  
<% end %>  

<% if alert && !alert.empty? %>
  <div class="alert alert-danger" role="alert">
    <span class="alert"><%= alert %></span>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to 'Stock', root_path, class: 'navbar-brand' %>

    <% if current_user %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
            <%= link_to 'My Portfolio', my_portfolio_path, class: 'nav-link' %>
          </li>
          <li class="nav-item <%= 'active' if request.path == my_friends_path %>">
            <%= link_to 'My Friends', my_friends_path, class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Profile
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                <i class="fa fa-pencil-alt"></i>
                Edit Profile 
              <% end %>  
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <li class="nav-item active user-name mr-3">
            <i class="fa fa-user"></i>
            <%= current_user.first_name %> <%= current_user.last_name %>
          </li>
          <li class="nav-item active">
            <%= link_to("Logout", destroy_user_session_path,
                class: "btn btn-xs btn-info mr-3", method: :delete) %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    <% end %>  
  </div>  
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stock</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <div class="container" id="content_container">
      <%= render "layouts/messages" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-9">
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |stock| %>
          <tr>
            <th scope="row"><%= stock.ticker %></th>
            <td><%= stock.name %></td>
            <td><%= stock.last_price %></td>
            <td>
              <% if current_user.id != @user.id %>
                <% if current_user.can_track_another_stock?(current_user, stock.ticker) && !current_user.stock_already_tracked?(stock.ticker) %>
                  <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: stock.ticker),
                              class: "btn btn-xs btn-success", method: :post %>
                <% else %>
                  <span class="badge badge-secondary">
                    You are already tracking
                    <% if !current_user.under_stock_limit?(current_user) %>
                      10 stocks.
                    <% end %>
                    <% if current_user.stock_already_tracked?(current_user, stock.ticker) %>  
                      this stock.
                    <% end %> 
                  </span>
                <% end %>
              <% elsif current_user.id == @user.id %>
                <%= link_to 'Remove', user_stock_path(stock), method: :delete, 
                    data: {confirm: 'Are you sure?'},
                    class: 'btn btn-sm btn-warning' %>
              <% end %>
            </td>          
          </tr>
        <% end %>  
      </tbody>
    </table>
  </div>
</div>

app/views/users/_friend_result.html.erb
<div class ="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @friends %>
  <strong>Search Results: </strong>

  <div class="card card-header results-block">
    <table>
      <thead>
        <tr>
          <th> Name </th>
          <th> Email </th>
          <th> Actions </th>
        </tr>
      </thead>
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <td>
              <%= friend.first_name + ' ' + friend.last_name %> 
            </td>
            <td> 
            <%= friend.email %>
            </td>
            <td>
              <%= link_to 'View Profile', user_path(id: friend.id),
                          class: "btn btn-xs btn-success" %> 

              <% if current_user.friend_already_displayed?(friend) %> 
                <span class="badge badge-secondary">
                  You are friends
                </span>
              <% elsif !current_user.under_friend_limit? %> 
                <span class="badge badge-secondary">
                  You already track 10 friends
                </span>
              <% else %>
                <%= link_to 'Follow', 
                            user_friends_path(user: current_user, friend: friend.id),
                            class: "btn btn-xs btn-success", method: :post %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>    
  </div>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#friend_results')
        .innerHTML = '<%= escape_javascript(render 'users/friend_result.html') %>'

app/views/users/_result.html.erb
<div class ="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
  <div class="card card-header results-block">
    <span style="display: inline-block; width:120px;"><strong>Symbol: </strong> <%= @stock.ticker %></span>
    <span style="display: inline-block; width:310px;"><strong>Name: </strong> <%= @stock.name %></span>
    <span style="display: inline-block; width:140px;"><strong>Last Price: </strong> <%= @stock.last_price %></span>
    <% if current_user.can_track_another_stock?(@stock.ticker) %>
      <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker),
                  class: "btn btn-xs btn-success", method: :post %>
    <% else %>
      <span class="badge badge-secondary">
        You are already tracking
        <% if !current_user.under_stock_limit? %>
          10 stocks.
        <% end %>
        <% if current_user.stock_already_tracked?(@stock.ticker) %>  
          this stock.
        <% end %> 
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_stock_result.html.erb
<div class ="results-block">
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
  <div class="card card-header results-block">
    <span style="display: inline-block; width:120px;"><strong>Symbol: </strong> <%= @stock.ticker %></span>
    <span style="display: inline-block; width:310px;"><strong>Name: </strong> <%= @stock.name %></span>
    <span style="display: inline-block; width:140px;"><strong>Last Price: </strong> <%= @stock.last_price %></span>
    <% if current_user.can_track_another_stock?(current_user, @stock.ticker) %>
      <%= link_to 'Add to portfolio', user_stocks_path(user: current_user, ticker: @stock.ticker),
                  class: "btn btn-xs btn-success", method: :post %>
    <% else %>
      <span class="badge badge-secondary">
        You are already tracking
        <% if !current_user.under_stock_limit?(current_user) %>
          10 stocks.
        <% end %>
        <% if current_user.stock_already_tracked?(current_user, @stock.ticker) %>  
          this stock.
        <% end %> 
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_stock_result.js.erb
document.querySelector('#stock_results')
        .innerHTML = '<%= escape_javascript(render 'users/stock_result.html') %>'

app/views/users/my_friends.html.erb
<h1>My Friends</h1>

<div class="search-area">
  <h3>Search Friends</h3>
  <%= form_tag 'search_friend', remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 padding-right-0">
        <%= text_field_tag :friend, params[:friend], placeholder: "Friend's name", 
                           autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 padding-left-0">
        <%= button_tag type: :submit, class: "btn btn-outline-info friend_search_btn" do %>
          <i class="fa fa-search" style="font-size: 2em;"></i>
        <% end %>  
      </div>
    </div>
  <% end %>
</div>

<div id="friend_results">
</div>

<% if !@tracked_friends.empty? %>
  <div class="friends-table-margin-top"></div
  <%= render 'friends/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>

<div class="search-area">
  <h3>Search Stocks</h3>
  <%= form_tag 'search_stock', remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 padding-right-0">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", 
                           autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 padding-left-0">
        <%= button_tag type: :submit, class: "btn btn-outline-info stock_search_btn" do %>
          <i class="fa fa-search" style="font-size: 2em;"></i>
        <% end %>  
      </div>
    </div>
  <% end %>
</div>

<div id="stock_results">   <!-- Search results are put into here -->
</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<h2>User Details</h2>

<div class="card card-header results-block">
  <p style="display: inline-block;">
    <strong>Name: </strong> <%= "#{@user.first_name} #{@user.last_name}" %>
    <strong>Email: </strong> <%= @user.email %>
  </p>

  <% if current_user.friend_already_displayed?(current_user, @user) %>
    <span class="badge badge-secondary">
      You are friends
    </span>
  <% elsif current_user.under_friend_limit?(current_user) %>  
    <%= link_to 'Follow', 
                user_friends_path(user: current_user, friend: @user.id),
                style: "display: inline-block;",
                class: "btn btn-xs btn-success", method: :post %>
  <% else %>
    <span class="badge badge-secondary">
      You already track 10 friends
    </span>
  <% end %>
</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% else %>
  <p class="lead">
    This user is not tracking any stocks
  </p>  
<% end %>

app/views/welcome/index.html.erb
<h4> Welcome to the Welcome page. </h4>

<%= link_to 'Sign out', destroy_user_session_path, method: :delete %>